name: docs

on:
  push:
    paths:
      - "docs/**"
      - ".github/workflows/docs.yml"
    branches:
      - main
  pull_request:
    paths:
      - "docs/**"
      - ".github/workflows/docs.yml"
    branches:
      - main

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20]

    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - name: Install pnpm.
        run: npm install pnpm -G

      - name: Install @root dependencies.
        run: pnpm install

      - name: Install @playground dependencies
        run: pnpm install
        working-directory: ./playground

      - name: Generate
        run: pnpm build
        working-directory: ./playground

      - name: Move dist folder
        run: mv ./dist ..
        working-directory: ./playground

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
